[package]
name = "srray"
version = "0.1.0"
authors = ["Evert Provoost <evert@elecprog.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "^0"
rayon= "^1"
